# Generated by Django 5.2 on 2025-04-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('cv', models.FileField(blank=True, help_text='Upload your résumé/CV (PDF)', null=True, upload_to='cv/')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('EXP', 'Expert'), ('ADV', 'Advanced'), ('INT', 'Intermediate'), ('BEG', 'Beginner')], default='IN', help_text='Select your proficiency level', max_length=3)),
            ],
            options={
                'ordering': ['-level'],
            },
        ),
        migrations.CreateModel(
            name='StatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('large_text', models.CharField(max_length=20, verbose_name='Big Number/Text')),
                ('small_text', models.CharField(max_length=50, verbose_name='Label')),
            ],
        ),
    ]
