# Generated by Django 5.2 on 2025-05-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(help_text='e.g. 2010', max_length=20, verbose_name='From')),
                ('end', models.CharField(help_text='e.g. present or 2013', max_length=20, verbose_name='To')),
                ('title', models.CharField(max_length=200, verbose_name='Role')),
                ('organization', models.CharField(max_length=200, verbose_name='Company')),
                ('description', models.TextField()),
                ('projects', models.TextField(blank=True, help_text='Comma-separated list of projects you worked on')),
                ('tech_stack', models.TextField(blank=True, help_text='Comma-separated list of technologies/tools used')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
            ],
            options={
                'ordering': ['order', '-start'],
            },
        ),
    ]
